### PR TITLE
Publish Microsoft Authored templates to azure samples browser

### PR DESCRIPTION
**Pull request by v-xuto**
Publish `azd-deployment-environments` template to azure samples browser.

@rajeshkamal5050, @hemarina for notification.

### CODE REVIEW

**Comment by v-xuto** [comment]
@wbreza  Could you help review this PR and merge it if it looks good?

**Comment by v-xuto** [comment]
@hemarina There is no product slug `azure-devcenter` in the [doc](https://review.learn.microsoft.com/en-us/help/platform/metadata-taxonomies?branch=main#product). Should we consider submitting a new slug request?

**Comment by v-xuto** [comment]
> @v-xuto Add `azure-devcenter` slug sounds reasonable. Could you submit a new slug request?

@hemarina According to [doc](https://review.learn.microsoft.com/en-us/help/platform/metadata-reporting-taxonomy-requests?branch=main), I have submitted the product slug `azure-devcenter` request in [form](https://forms.office.com/pages/responsepage.aspx?id=v4j5cvGGr0GRqy180BHbR2T0trbLoiBLqXeMiApKoFhURFo3NDFaRTdRSTVFUVo0TTk4RkJLNVRNVSQlQCN0PWcu), let's wait for its feedback results.

**Review by wbreza — COMMENTED** [review]
Looks good however I don't know much about these slugs.  Please let me know once you confirm.

**Comment by v-xuto** [comment]
@hemarina The slug request I submitted took effect in [doc](https://review.learn.microsoft.com/en-us/help/platform/metadata-taxonomies?branch=main#msservice), but `azure-devcenter` only appeared under `ms.service` and not under `product`. I'm not sure if this is enough? Currently, only these four categories ("ms. service, ms. subservice", "ms. devlang", "ms. author", and "ms. topic") can be added in this [form](https://forms.office.com/pages/responsepage.aspx?id=v4j5cvGGr0GRqy180BHbR2T0trbLoiBLqXeMiApKoFhURFo3NDFaRTdRSTVFUVo0TTk4RkJLNVRNVSQlQCN0PWcu), and `product` slug cannot be added. 
image

**Comment by v-xuto** [comment]
@hemarina Thank you very much for your clarification and explanation. Currently, the `azure-devcenter` slug has been added under the [ms.service slug](https://review.learn.microsoft.com/en-us/help/platform/metadata-taxonomies?branch=main#msservice).

@wbreza These slugs have been confirmed, please review this PR. If there is no issue, please help merge this PR.

**Comment by v-xuto** [comment]
@hemarina I have removed the product slug `azure-devcenter`. Please review.

**Review by wbreza — APPROVED** [review]

**Pull request merged**
